//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Web_Form {


    public partial class _232127_DelaCruz_AboutMe {
    }
}
