//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Web_Form {

    public partial class Site {
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    }
}
